FROM tiangolo/uvicorn-gunicorn:python3.10-slim
ENV PYTHONUNBUFFERED=1
WORKDIR /app
COPY requirements.txt /app
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN apt-get update -y
RUN apt-get install gcc -y
RUN pip install -r requirements.txt
COPY . /app

CMD gunicorn --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=$UVICORN_HOST:$UVICORN_PORT app.main:app